# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8963482f474003ee43fa902dd23528627bf406f2907787ac56c6252d26f1e1ef8f27ecb6390bb2ea0fb5cd2a06821625a37bfbc1316248d74808ca832069c7a

test:
  secret_key_base: 9d679c015c103802fa63c4de4ee44c11ef8d3d4a986bd1073916d4a6e96d708a157ce094f46e5c9d730e6300af0845967d766913d534128d65c04325d368bcff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
